# Generated by Django 2.2.1 on 2019-05-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='my_movies',
            field=models.ManyToManyField(default=None, null=True, to='api.Movie'),
        ),
    ]
